### ISSUE TITLE
MongoDB

### ISSUE THREAD

**Issue by kbillows** [kbillows/web-logs#6]
# 使用 MongoDB 开发过程常见错误分析
#### [url](https://mp.weixin.qq.com/s/qeczup6BWxEwAm4-8ZGGHw)

- Mongo shell 中使用大整数字面量
- 片键使用自增长字段
- 程序里游标循环迭代过程中进行长时间的操作
- 滥用数组类型
- 滥用 upsert 更新参数
- 错误的设计索引
- 错误的认为复制等于备份

**Comment by kbillows** [comment]
### Windows 服务的安装与卸载

安装执行如下命令：
```
mongod.exe --bind_ip yourIPadress --logpath "C:\data\dbConf\mongodb.log" --logappend --dbpath "C:\data\db" --port yourPortNumber --serviceName "YourServiceName" --serviceDisplayName "YourServiceName" --install
```
eg.
```
mongod.exe --bind_ip 127.0.0.1 --logpath "C:\MongoDB\secondary3\log\mongodb.log" --logappend --dbpath "C:\MongoDB\secondary3\data" --port 29035 --serviceName "MongoDB_3.4.2_secondary3" --serviceDisplayName "mongo-sec3(29035)" --install
```
_注意：与旧版本不同的是，3.x的日志的配置是要一个具体的.log文件，而不再是一个目录就行了_
卸载执行如下命令：
```
mongod --remove --serviceName "MongoDB_3.4.2_secondary3"
```
### 添加用户

- 先切换到要添加用户的数据库：eg. ```use employee```
- 早期版本的写法 ```db.addUser("userName","password")```
- 现在版本的写法：```db.createUser({user:"userName",pwd:"password",roles:[]})```  需要有roles:[]参数
- 查看db状态：```db.staus()```


### 创建 view
```
rs1:PRIMARY> db.createView("empView1","employee",{$project:{"fName":"$FirstName","lName":"
$LastName"}})
```

### 搭建 replica  结构

1. 在同一级目录下创建primary、secondary1、secnodary2...等目录；
2. 在每个目录下创建data、log目录和mongod.cfg（配置文件）
3. 打开每个mongod.cfg，添加如下配置代码：
```
systemLog:
   quiet: false
   destination: file
   path: C:\\MongoDB\primary\\log\\mongodb.log
   logAppend: true
   logRotate: rename
net:
   port: 29031
   maxIncomingConnections: 65536  
   wireObjectCheck: true  
   ipv6: false 
storage:
   dbPath: C:\\MongoDB\primary\\data
   indexBuildRetry: true
   directoryPerDB: true
replication:
   oplogSizeMB: 20
   replSetName: rs1
--注意修改不同文件中systemLog节中的path值，net节中的port值和storage节点中dbPath的值。
```



4. 创建完上述的几个配置文件后，分别执行以下命令，完成每个实例的配置
```
mongod --config C:\MongoDB\secondaryX\mongod.cfg
```

5. replica 节点目录创建后，需要指定指定哪个是主的，选择需要指定为primary的实例进入，比如以29031为主，执行以下mongo命令：
```
\bin\mongo -port 29031
-- 等待连接完毕
rs.initiate() --会得到machineNamee及port信息
rs.config() --会指定哪一个是primary的
rs.add("machineName":29032) --添加secondary1
rs.add("machineName":29033) --添加secondary2
rs.status() --查看设置好之后的状态
/*
说明：29031,29032,29033是在安装不同mongoDB实例时指定的端口号。
*/
```

### 搭建 replication set 的步骤
1. 停掉3个mongodb的服务
2. 卸载3个mongodb的服务
3. 修改三个目录的配置文件，加上replication节点
4. 重新安装3个mongodb服务


### 查询
1. 查询指定字段
```db.coll.find({},{"Name":1,"Age":0,"_id":0}) ```//查询 Name，但不查询 Age, _id 要特殊指定，否则默认会查询
2. 模糊查询
```db.coll.find({"Name":'/.kb*/'})``` //以 kb 开头的，类似 SQL 中的 like
3. 非查询
```db.coll.find({$nor:["Name":'kbillows']}) ```//not
4. 正则匹配查询
5. 排序
```db.coll.find({"Name":'kbillows'}).sort({"Age":1})``` // 按 Age 排序，1正序(asc) | -1倒序(desc)
6. Top
```db.coll.find({"Name":'kbillows'}).sort().limit(count)``` //排序后，取前 count 条记录
7. 比较 $lt,$lte,$gt,$gte
```db.coll.find({"Age":{$lt:30}});``` // 查询年龄小于30岁的人
